---
- name: Install required packages
  apt:
    pkg:
      - php-mysql
      - python3-pip
      - mysql-client
      - mysql-server
    state: present

- name: Make sure pymysql is present
  become: yes
  pip:
    name: pymysql
    state: present

- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  tags: mysql
  become: yes

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  mysql/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes
  tags: mysql
  notify: restart mysql

- name: create mysql config
  template:
    src:  mysql/database.cnf.j2
    dest: /etc/mysql/conf.d/database.cnf
    owner: root
    mode: 0600
  become: yes
  tags: mysql
  notify: restart mysql

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  loop: "{{ mysql.hosts }}"
  become: yes
  tags: mysql
  notify: restart mysql

- name: Create Laravel database
  mysql_db:
    name: "{{ mysql.database }}"
    state: present
  tags: mysql

- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    login_user: root
    #login_password:
  with_items: "{{ mysql_users }}"
  tags: mysql
#  no_log: true
