Vagrant.configure("2") do |config|
    config.vm.define "webshop" do |gitlab|
        gitlab.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "4096"]
            vb.customize ["modifyvm", :id, "--cpus", "4"]
        end
        gitlab.vm.box = "ubuntu/bionic64"
        gitlab.vm.hostname = "webshop"
        gitlab.ssh.insert_key = false

        gitlab.vm.network :private_network, ip: "192.168.100.101"
        gitlab.vm.provision "lamp", type: "ansible" do |ansible|
            ansible.inventory_path = "inventories/testing"
            #ansible.verbose = "v"
            ansible.playbook = "lamp.yml"
            ansible.limit = "lamp"
            ansible.extra_vars = {
                gitlab_external_url: "https://192.168.100.101/"
            }
            ansible.become = true
            ansible.host_key_checking = false
        end
    end
end